using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GeneratSettings
{
    //Because the code is automatically generated by my own Code Generator, press (ctrl + K + D) to organize the code .    
    //For More Detailes Visit My Account On GitHub : https://github.com/BilalAljaddoua . (-; 
    public class clsDataAccessSettings
    { 
        //Please chanfe the user id and the password to fit your settings...
        public static string ConnectionString = "Server=.;Database=Library;User Id=sa;Password=123456;Encrypt=False;TrustServerCertificate=True;Connection Timeout=30;";

 
    }
}
